
tasks:
  - name: Angular CLI
    init: npm install -g @angular/cli
  
  - name: Prepare Development
    init: npm install
    command: npm run start-gitpod
ports:
  - port: 4200
    onOpen: open-browser
vscode:
  extensions:
    - angular.ng-template