
tasks:
  - name: Angular CLI
    init: npm install -g @angular/cli
  
  - name: Prepare Development
    init: npm install
    command: npm run start-gitpod
  
  - name: HTTP Server
    init: npm install -g http-server
ports:
  - port: 4200
    onOpen: open-browser
    visibility: public
vscode:
  extensions:
    - angular.ng-template